[package]
name = "oscillot"
version = "0.1.0"
authors = ["ckinloch"]
build = "build.rs"

[dependencies]
gdk = "^0"
glib = "^0"
cairo-rs = "^0"

jack = "^0"

[dependencies.gio]
version = "^0"
features = ["v2_44"]

[dependencies.gtk]
version = "^0"
features = ["v3_16"]
